config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "mainpages#index", as: "home"

  # harusnya only guest
  get "login", to: "login#index", as: "login"
  post "login/store", to: "login#store", as: "loginstore"
  get "forgotpassword", to: "login#forgotpass", as: "forgotpassword"
  post "forgotpassword/store", to: "login#forgotpassstore", as: "forgotpasswordstore"
  get "forgotpassword/edit", to: "login#forgotpassedit", as: "forgotpassedit"
  patch "forgotpassword/update", to: "login#forgotpassupdate", as: "forgotpassupdate"

  delete "logout", to: "login#logout", as: "logout"

  # harusnya only admin
  namespace :admin do
    get "dashboard", to: "dashboard#index", as: "dashboard"

    #crud genre
    get "genre", to: "genre#index", as: "genre_index"
    get "genre/add", to: "genre#add", as: "genre_add"
    post "genre/store", to: "genre#store", as: "genre_store"
    get "genre/destroy/:id", to: "genre#destroy", as: "genre_delete"
    get "genre/edit/:id", to: "genre#edit", as: "genre_edit"
    patch "genre/edit/:id", to: "genre#update", as: "genre_update"

    #crud lokasi
    get "location", to: "lokasi#index", as: "location_index"
    get "location/add", to: "lokasi#add", as: "location_add"
    post "location/store", to: "lokasi#store", as: "location_store"
    get "location/destroy/:id", to: "lokasi#destroy", as: "location_delete"
    get "location/edit/:id", to: "lokasi#edit", as: "location_edit"
    patch "location/update/:id", to: "lokasi#update", as: "location_update"

    #crud tipe
    get "type", to: "tipe#index", as: "type_index"
    get "type/add", to: "tipe#add", as: "type_add"
    post "type/store", to: "tipe#store", as: "type_store"
    get "type/destroy/:id", to: "tipe#destroy", as: "type_delete"
    get "type/edit/:id", to: "tipe#edit", as: "type_edit"
    patch "type/update/:id", to: "tipe#update", as: "type_update"

    #crud member
    get "member", to: "member#index", as: "member_index"
    get "member/add", to: "member#add", as: "member_add"
    post "member/store", to: "member#store", as: "member_store"
    get "member/destroy/:id", to: "member#destroy", as: "member_delete"
    get "member/edit/:id", to: "member#edit", as: "member_edit"
    patch "member/update/:id", to: "member#update", as: "member_update"

    #crud buku
    get "book", to: "book#index", as: "book_index"
    get "book/add", to: "book#add", as: "book_add"
    post "book/store", to: "book#store", as: "book_store"
    get "book/destroy/:id", to: "book#destroy", as: "book_delete"
    get "book/edit/:id", to: "book#edit", as: "book_edit"
    patch "book/update/:id", to: "book#update", as: "book_update"

    #crud buku
    get "borrower", to: "borrower#index", as: "borrower_index"
    get "borrower/add", to: "borrower#add", as: "borrower_add"
    post "borrower/store", to: "borrower#store", as: "borrower_store"
    get "borrower/return/:id", to: "borrower#return", as: "borrower_return"
  end

  # api
  namespace :api, defaults: { format: :json } do
    post "authenticate", to: "authentication#authenticate"
    resources :trips, only: [:index]
  end
end

app/models/member.rb
class Member < ApplicationRecord
  paginates_per 10
  acts_as_paranoid

  validates :nik, presence: true
  validates :name, presence: true
  validates :email, uniqueness: true, presence: true
  mount_uploader :photo, MemberPhotoUploader
end

app/controllers/admin/member_controller.rb
class Admin::MemberController < ApplicationController
  before_action :check_user_login
  layout "admin"

  def index
    @members = Member.where("name like ?", "%#{params[:search]}%").order(:name).page params[:page]

    if params.has_key?(:page)
      perpage = 10
      page = Integer(params[:page])
      @no = (page * perpage) - perpage
    else
      @no = 0
    end
  end

  def add
    @member = Member.new
  end

  def store
    @member = Member.new(member_params)
    if @member.save
      redirect_to admin_member_index_path, flash: { :message => "Menambah Member Berhasil", :type => "success" }
    else
      render :add
    end
  end

  def edit
    @member = Member.find(params[:id]) rescue nil
    if @member.nil?
      redirect_to admin_member_index_path, flash: { :message => "Data Tidak ditemukan", :type => "warning" }
    end
    @member.photo.cache!
  end

  def update
    @member = Member.find(params[:id]) rescue nil
    if @member.nil?
      redirect_to admin_member_index_path, flash: { :message => "Data Tidak ditemukan", :type => "warning" }
    end

    if @member.update(member_params)
      redirect_to admin_member_index_path, flash: { :message => "Mengubah Member Berhasil", :type => "success" }
    else
      render :edit
    end
  end

  def destroy
    @member = Member.find(params[:id]) rescue nil
    if !@member.nil?
      @member.remove_photo!
      @member.save
      @member.destroy
      redirect_to admin_member_index_path, flash: { :message => "Menghapus Member Berhasil", :type => "success" }
    else
      redirect_to admin_member_index_path, flash: { :message => "Data Tidak ditemukan", :type => "warning" }
    end
  end

  def member_params
    params.required(:member).permit(:nik, :name, :email, :phone, :gender, :address, :photo)
  end
end

app/helpers/admin/member_helper.rb
module Admin::MemberHelper
end

app/views/admin/member/add.html.erb
<% content_for :title, "Member Add" %>
<h1 class="page-header mb-3">Tambah Member</h1>
<div class="row">
  <div class="col-xl-12">
    <div class="card">
      <div class="card-body">
        <%= render partial: "shared/alertmainpage" %>
        <br />
        <%= form_with model:@member, url: admin_member_store_path, method: :post,
        multipart:true do |form| %>
        <div class="form-row row">
          <div class="form-group col-md-6">
            <% invalid = @member.errors.include?(:nik) %>
            <label for="inputPassword4">NIK</label>
            <%= form.text_field :nik, class:"form-control #{if invalid then
            "is-invalid" else "" end }", placeholder:"1928369" %> <% if invalid
            %>
            <div class="invalid-feedback d-block">
              <% @member.errors.full_messages_for(:nik).each do |error_message|
              %> <%= error_message %>. <br />
              <% end %>
            </div>
            <% end %>
          </div>
          <div class="form-group col-md-6">
            <% invalid = @member.errors.include?(:name) %>
            <label for="inputEmail4">Nama</label>
            <%= form.text_field :name, class:"form-control #{if invalid then
            "is-invalid" else "" end }", placeholder:"Asep" %> <% if invalid %>
            <div class="invalid-feedback d-block">
              <% @member.errors.full_messages_for(:name).each do |error_message|
              %> <%= error_message %>. <br />
              <% end %>
            </div>
            <% end %>
          </div>
        </div>
        <div class="form-row row mt-3">
          <div class="form-group col-md-6">
            <% invalid = @member.errors.include?(:email) %>
            <label for="inputPassword4">E-mail</label>
            <%= form.text_field :email, class:"form-control #{if invalid then
            "is-invalid" else "" end }", placeholder:"1928369" %> <% if invalid
            %>
            <div class="invalid-feedback d-block">
              <% @member.errors.full_messages_for(:email).each do
              |error_message| %> <%= error_message %>. <br />
              <% end %>
            </div>
            <% end %>
          </div>
          <div class="form-group col-md-6">
            <% invalid = @member.errors.include?(:phone) %>
            <label for="inputEmail4">No Telepon</label>
            <%= form.text_field :phone, class:"form-control #{if invalid then
            "is-invalid" else "" end }", placeholder:"0892456152347" %> <% if
            invalid %>
            <div class="invalid-feedback d-block">
              <% @member.errors.full_messages_for(:phone).each do
              |error_message| %> <%= error_message %>. <br />
              <% end %>
            </div>
            <% end %>
          </div>
        </div>
        <div class="form-row row mt-3">
          <div class="form-group col-md-6">
            <% invalid = @member.errors.include?(:place_birth) %>
            <label for="inputPassword4">Tempat Lahir</label>
            <%= form.text_field :place_birth, class:"form-control #{if invalid
            then "is-invalid" else "" end }", placeholder:"Jakarta" %> <% if
            invalid %>
            <div class="invalid-feedback d-block">
              <% @member.errors.full_messages_for(:place_birth).each do
              |error_message| %> <%= error_message %>. <br />
              <% end %>
            </div>
            <% end %>
          </div>
          <div class="form-group col-md-6">
            <% invalid = @member.errors.include?(:date_birth) %>
            <label for="inputEmail4">Tanggal Lahir</label>
            <%= form.date_field :date_birth, class:"form-control #{if invalid
            then "is-invalid" else "" end }", placeholder:"2017/03/01" %> <% if
            invalid %>
            <div class="invalid-feedback d-block">
              <% @member.errors.full_messages_for(:date_birth).each do
              |error_message| %> <%= error_message %>. <br />
              <% end %>
            </div>
            <% end %>
          </div>
        </div>
        <div class="form-row row mt-3">
          <div class="form-group col-md-6">
            <% invalid = @member.errors.include?(:blood_type) %>
            <label for="inputPassword4">Golongan Darah</label>
            <%= form.text_field :blood_type, class:"form-control #{if invalid
            then "is-invalid" else "" end }", placeholder:"A" %> <% if invalid
            %>
            <div class="invalid-feedback d-block">
              <% @member.errors.full_messages_for(:blood_type).each do
              |error_message| %> <%= error_message %>. <br />
              <% end %>
            </div>
            <% end %>
          </div>
          <div class="form-group col-md-6">
            <% invalid = @member.errors.include?(:gender) %>
            <label for="inputEmail4">Jenis Kelamin</label>
            <%= form.select :gender, ["Laki -laki", "Perempuan"],{},
            class:"form-control #{if invalid then "is-invalid" else "" end }",
            placeholder:"Pilih Jenis Kelamin" %> <% if invalid %>
            <div class="invalid-feedback d-block">
              <% @member.errors.full_messages_for(:gender).each do
              |error_message| %> <%= error_message %>. <br />
              <% end %>
            </div>
            <% end %>
          </div>
        </div>
        <div class="form-row row mt-3">
          <div class="form-group col-md-6">
            <% invalid = @member.errors.include?(:religion) %>
            <label for="inputPassword4">Agama</label>
            <%= form.text_field :religion, class:"form-control #{if invalid then
            "is-invalid" else "" end }", placeholder:"Islam" %> <% if invalid %>
            <div class="invalid-feedback d-block">
              <% @member.errors.full_messages_for(:religion).each do
              |error_message| %> <%= error_message %>. <br />
              <% end %>
            </div>
            <% end %>
          </div>
          <div class="form-group col-md-6">
            <% invalid = @member.errors.include?(:photo) %>
            <label for="inputEmail4">Foto Member</label>
            <%= form.file_field :photo, class:"form-control #{if invalid then
            "is-invalid" else "" end }", placeholder:"Islam" %> <% if invalid %>
            <div class="invalid-feedback d-block">
              <% @member.errors.full_messages_for(:photo).each do
              |error_message| %> <%= error_message %>. <br />
              <% end %>
            </div>
            <% end %>
          </div>
        </div>
        <div class="form-group col-md-12 mt-3">
          <% invalid = @member.errors.include?(:address) %>
          <label for="inputPassword4">Alamat</label>
          <%= form.text_area :address, class:"form-control #{if invalid then
          "is-invalid" else "" end }", placeholder:"Jln kota bandung" %> <% if
          invalid %>
          <div class="invalid-feedback d-block">
            <% @member.errors.full_messages_for(:address).each do
            |error_message| %> <%= error_message %>. <br />
            <% end %>
          </div>
          <% end %>
        </div>
        <hr />
        <div class="text-end">
          <a href="<%= admin_member_index_path %>" class="btn btn-danger">
            Batal
          </a>
          <%= form.submit "Simpan", class:"btn btn-primary" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<!-- END row -->

<% content_for :javascript do %>
<script>
  CKEDITOR.replace("member_address");
</script>
<script>
  $(document).ready(function () {
    $("#member_gender").select2({
      placeholder: "Pilih Jenis Kelamin",
      allowClear: true,
    });
  });
</script>
<% end %>

app/views/admin/member/edit.html.erb
<% content_for :title, "Member Edit" %>
<h1 class="page-header mb-3">Edit Member</h1>
<div class="row">
  <div class="col-xl-12">
    <div class="card">
      <div class="card-body">
        <%= render partial: "shared/alertmainpage" %>
        <br />
        <%= form_with model:@member, url: admin_member_update_path, method:
        :patch, multipart:true do |form| %>
        <div class="form-row row">
          <div class="form-group col-md-6">
            <% invalid = @member.errors.include?(:nik) %>
            <label for="inputPassword4">NIK</label>
            <%= form.text_field :nik, class:"form-control #{if invalid then
            "is-invalid" else "" end }", placeholder:"1928369" %> <% if invalid
            %>
            <div class="invalid-feedback d-block">
              <% @member.errors.full_messages_for(:nik).each do |error_message|
              %> <%= error_message %>. <br />
              <% end %>
            </div>
            <% end %>
          </div>
          <div class="form-group col-md-6">
            <% invalid = @member.errors.include?(:name) %>
            <label for="inputEmail4">Nama</label>
            <%= form.text_field :name, class:"form-control #{if invalid then
            "is-invalid" else "" end }", placeholder:"Asep" %> <% if invalid %>
            <div class="invalid-feedback d-block">
              <% @member.errors.full_messages_for(:name).each do |error_message|
              %> <%= error_message %>. <br />
              <% end %>
            </div>
            <% end %>
          </div>
        </div>
        <div class="form-row row mt-3">
          <div class="form-group col-md-6">
            <% invalid = @member.errors.include?(:email) %>
            <label for="inputPassword4">E-mail</label>
            <%= form.text_field :email, class:"form-control #{if invalid then
            "is-invalid" else "" end }", placeholder:"1928369" %> <% if invalid
            %>
            <div class="invalid-feedback d-block">
              <% @member.errors.full_messages_for(:email).each do
              |error_message| %> <%= error_message %>. <br />
              <% end %>
            </div>
            <% end %>
          </div>
          <div class="form-group col-md-6">
            <% invalid = @member.errors.include?(:phone) %>
            <label for="inputEmail4">No Telepon</label>
            <%= form.text_field :phone, class:"form-control #{if invalid then
            "is-invalid" else "" end }", placeholder:"0892456152347" %> <% if
            invalid %>
            <div class="invalid-feedback d-block">
              <% @member.errors.full_messages_for(:phone).each do
              |error_message| %> <%= error_message %>. <br />
              <% end %>
            </div>
            <% end %>
          </div>
        </div>
        <div class="form-row row mt-3">
          <div class="form-group col-md-6">
            <% invalid = @member.errors.include?(:place_birth) %>
            <label for="inputPassword4">Tempat Lahir</label>
            <%= form.text_field :place_birth, class:"form-control #{if invalid
            then "is-invalid" else "" end }", placeholder:"Jakarta" %> <% if
            invalid %>
            <div class="invalid-feedback d-block">
              <% @member.errors.full_messages_for(:place_birth).each do
              |error_message| %> <%= error_message %>. <br />
              <% end %>
            </div>
            <% end %>
          </div>
          <div class="form-group col-md-6">
            <% invalid = @member.errors.include?(:date_birth) %>
            <label for="inputEmail4">Tanggal Lahir</label>
            <%= form.date_field :date_birth, class:"form-control #{if invalid
            then "is-invalid" else "" end }", placeholder:"2017/03/01" %> <% if
            invalid %>
            <div class="invalid-feedback d-block">
              <% @member.errors.full_messages_for(:date_birth).each do
              |error_message| %> <%= error_message %>. <br />
              <% end %>
            </div>
            <% end %>
          </div>
        </div>
        <div class="form-row row mt-3">
          <div class="form-group col-md-6">
            <% invalid = @member.errors.include?(:blood_type) %>
            <label for="inputPassword4">Golongan Darah</label>
            <%= form.text_field :blood_type, class:"form-control #{if invalid
            then "is-invalid" else "" end }", placeholder:"A" %> <% if invalid
            %>
            <div class="invalid-feedback d-block">
              <% @member.errors.full_messages_for(:blood_type).each do
              |error_message| %> <%= error_message %>. <br />
              <% end %>
            </div>
            <% end %>
          </div>
          <div class="form-group col-md-6">
            <% invalid = @member.errors.include?(:gender) %>
            <label for="inputEmail4">Jenis Kelamin</label>
            <%= form.select :gender, ["Laki -laki", "Perempuan"],{},
            class:"form-control #{if invalid then "is-invalid" else "" end }",
            placeholder:"Pilih Jenis Kelamin" %> <% if invalid %>
            <div class="invalid-feedback d-block">
              <% @member.errors.full_messages_for(:gender).each do
              |error_message| %> <%= error_message %>. <br />
              <% end %>
            </div>
            <% end %>
          </div>
        </div>
        <div class="form-row row mt-3">
          <div class="form-group col-md-6">
            <% invalid = @member.errors.include?(:religion) %>
            <label for="inputPassword4">Agama</label>
            <%= form.text_field :religion, class:"form-control #{if invalid then
            "is-invalid" else "" end }", placeholder:"Islam" %> <% if invalid %>
            <div class="invalid-feedback d-block">
              <% @member.errors.full_messages_for(:religion).each do
              |error_message| %> <%= error_message %>. <br />
              <% end %>
            </div>
            <% end %>
          </div>
          <div class="form-group col-md-6">
            <% invalid = @member.errors.include?(:photo) %>
            <label for="inputEmail4">Foto Member</label>
            <%= form.file_field :photo, class:"form-control #{if invalid then
            "is-invalid" else "" end }", placeholder:"Islam" %>
            <%= form.hidden_field :photo_cache %>
            <% if invalid %>
            <div class="invalid-feedback d-block">
              <% @member.errors.full_messages_for(:photo).each do
              |error_message| %> <%= error_message %>. <br />
              <% end %>
            </div>
            <% end %>
          </div>
        </div>
        <div class="form-group col-md-12 mt-3">
          <% invalid = @member.errors.include?(:address) %>
          <label for="inputPassword4">Alamat</label>
          <%= form.text_area :address, class:"form-control #{if invalid then
          "is-invalid" else "" end }", placeholder:"Jln kota bandung" %> <% if
          invalid %>
          <div class="invalid-feedback d-block">
            <% @member.errors.full_messages_for(:address).each do
            |error_message| %> <%= error_message %>. <br />
            <% end %>
          </div>
          <% end %>
        </div>
        <hr />
        <div class="text-end">
          <a href="<%= admin_member_index_path %>" class="btn btn-danger">
            Batal
          </a>
          <%= form.submit "Simpan", class:"btn btn-primary" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<!-- END row -->

<% content_for :javascript do %>
<script>
  CKEDITOR.replace("member_address");
</script>
<script>
  $(document).ready(function () {
    $("#member_gender").select2({
      placeholder: "Pilih Jenis Kelamin",
      allowClear: true,
    });
  });
</script>
<% end %>

app/views/admin/member/index.html.erb
<% content_for :title, "Member" %>
<h1 class="page-header mb-3">List Member</h1>
<div class="row">
  <div class="col-xl-12">
    <div class="card">
      <div class="card-header row">
        <div class="col-md-8">
          <a href="<%= admin_member_add_path %>" class="btn btn-primary"
            ><i class="fa fa-plus"></i> Tambah Member</a
          >
        </div>
        <div class="col-md-4">
          <div class="text-end">
            <form action="" method="get">
              <div class="input-group">
                <input
                  type="search"
                  class="form-control"
                  name="search"
                  value="<%= params[:search] %>"
                  placeholder="Cari...."
                />
                <div class="input-group-append">
                  <button type="submit" class="btn btn-primary">
                    <i class="fa fa-search"></i> Cari
                  </button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
      <div class="card-body">
        <%= render partial: "shared/alertmainpage" %>
        <div class="table-responsive">
          <table class="table table-striped">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">NIK</th>
                <th scope="col">Nama</th>
                <th scope="col">Tempat Lahir</th>
                <th scope="col">Tanggal Lahir</th>
                <th scope="col">Jenis Kelamin</th>
                <th scope="col">Tanggal Dibuat</th>
                <th scope="col">photo</th>
                <th scope="col">Aksi</th>
              </tr>
            </thead>
            <tbody>
              <% @members.each do |member| %>
              <tr>
                <td><%= @no+=1 %></td>
                <td><%= member.nik %></td>
                <td><%= member.name %></td>
                <td><%= member.place_birth %></td>
                <td><%= member.date_birth %></td>
                <td><%= member.gender %></td>
                <td><%= member.created_at.strftime('%d %b %Y - %H:%M') %></td>
                <td><img src="<%= member.photo %>" width="100"></td>
                <td>
                  <a
                    href="<%= admin_member_edit_path(member.id) %>"
                    class="btn btn-sm btn-primary"
                    ><i class="fa fa-edit"></i> Edit</a
                  >
                  <button
                    data-delete="<%= admin_member_delete_path(member.id) %>"
                    class="btn btn-sm btn-danger btndelete"
                  >
                    <i class="fa fa-trash"></i> Hapus
                  </button>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <div style="display: flex; justify-content: center">
          <%= paginate @members, inner_window: 3 %>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- END row -->

<% content_for :javascript do %>
<script>
  $(".btndelete").click(function () {
    var linkdelete = $(this).data("delete");
    const swalWithBootstrapButtons = Swal.mixin({
      customClass: {
        confirmButton: "btn btn-danger",
        cancelButton: "btn btn-success mr-1",
      },
      buttonsStyling: {
        cancelButton: "margin-right: 1rem;",
      },
    });

    swalWithBootstrapButtons
      .fire({
        title: "Apakah Yakin Ingin ?",
        text: "Ingin Menghapus Data Tersebut",
        icon: "warning",
        showCancelButton: true,
        confirmButtonText: "Hapus",
        cancelButtonText: "Batal",
        reverseButtons: true,
      })
      .then((result) => {
        if (result.isConfirmed) {
          window.location.href = linkdelete;
        }
      });
  });
</script>
<% end %>