config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "mainpages#index", as: "home"

  # harusnya only guest
  get "login", to: "login#index", as: "login"
  post "login/store", to: "login#store", as: "loginstore"
  get "forgotpassword", to: "login#forgotpass", as: "forgotpassword"
  post "forgotpassword/store", to: "login#forgotpassstore", as: "forgotpasswordstore"
  get "forgotpassword/edit", to: "login#forgotpassedit", as: "forgotpassedit"
  patch "forgotpassword/update", to: "login#forgotpassupdate", as: "forgotpassupdate"

  delete "logout", to: "login#logout", as: "logout"

  # harusnya only admin
  namespace :admin do
    get "dashboard", to: "dashboard#index", as: "dashboard"

    #crud genre
    get "genre", to: "genre#index", as: "genre_index"
    get "genre/add", to: "genre#add", as: "genre_add"
    post "genre/store", to: "genre#store", as: "genre_store"
    get "genre/destroy/:id", to: "genre#destroy", as: "genre_delete"
    get "genre/edit/:id", to: "genre#edit", as: "genre_edit"
    patch "genre/edit/:id", to: "genre#update", as: "genre_update"

    #crud lokasi
    get "location", to: "lokasi#index", as: "location_index"
    get "location/add", to: "lokasi#add", as: "location_add"
    post "location/store", to: "lokasi#store", as: "location_store"
    get "location/destroy/:id", to: "lokasi#destroy", as: "location_delete"
    get "location/edit/:id", to: "lokasi#edit", as: "location_edit"
    patch "location/update/:id", to: "lokasi#update", as: "location_update"

    #crud tipe
    get "type", to: "tipe#index", as: "type_index"
    get "type/add", to: "tipe#add", as: "type_add"
    post "type/store", to: "tipe#store", as: "type_store"
    get "type/destroy/:id", to: "tipe#destroy", as: "type_delete"
    get "type/edit/:id", to: "tipe#edit", as: "type_edit"
    patch "type/update/:id", to: "tipe#update", as: "type_update"

    #crud member
    get "member", to: "member#index", as: "member_index"
    get "member/add", to: "member#add", as: "member_add"
    post "member/store", to: "member#store", as: "member_store"
    get "member/destroy/:id", to: "member#destroy", as: "member_delete"
    get "member/edit/:id", to: "member#edit", as: "member_edit"
    patch "member/update/:id", to: "member#update", as: "member_update"

    #crud buku
    get "book", to: "book#index", as: "book_index"
    get "book/add", to: "book#add", as: "book_add"
    post "book/store", to: "book#store", as: "book_store"
    get "book/destroy/:id", to: "book#destroy", as: "book_delete"
    get "book/edit/:id", to: "book#edit", as: "book_edit"
    patch "book/update/:id", to: "book#update", as: "book_update"

    #crud buku
    get "borrower", to: "borrower#index", as: "borrower_index"
    get "borrower/add", to: "borrower#add", as: "borrower_add"
    post "borrower/store", to: "borrower#store", as: "borrower_store"
    get "borrower/return/:id", to: "borrower#return", as: "borrower_return"
  end

  # api
  namespace :api, defaults: { format: :json } do
    post "authenticate", to: "authentication#authenticate"
    resources :trips, only: [:index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  paginates_per 10
  acts_as_paranoid

  has_many :book_categories

  validates :location_id, presence: true
  validates :type_id, presence: true
  validates :name, presence: true
  validates :book_total, presence: true
  validates :book_total_remaining, presence: true
  mount_uploader :bookphoto, MemberPhotoUploader
end

app/models/book_category.rb
class BookCategory < ApplicationRecord
  paginates_per 10
  acts_as_paranoid

  belongs_to :book
  belongs_to :genre

  validates :book_id, presence: true
  validates :genre_id, presence: true
end

app/models/borrower.rb
class Borrower < ApplicationRecord
  paginates_per 10
  acts_as_paranoid

  belongs_to :book
  belongs_to :member

  validates :book_id, presence: true
  validates :member_id, presence: true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/genre.rb
class Genre < ApplicationRecord
  paginates_per 10
  acts_as_paranoid

  validates :name, presence: true
end

app/models/location.rb
class Location < ApplicationRecord
  paginates_per 10
  acts_as_paranoid

  validates :name, presence: true
end

app/models/member.rb
class Member < ApplicationRecord
  paginates_per 10
  acts_as_paranoid

  validates :nik, presence: true
  validates :name, presence: true
  validates :email, uniqueness: true, presence: true
  mount_uploader :photo, MemberPhotoUploader
end

app/models/type.rb
class Type < ApplicationRecord
    paginates_per 10
    acts_as_paranoid
  
    validates :name, presence: true
end

app/models/user.rb
# email:string
# name:string
# password_digest:string
#
# password:string virtual by has_secure_password
# password_confirmation:string virtual by has_secure_password
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_secure_password

  # validation
  validates :name, presence: true
  validates :password, length: { minimum: 8 }
  validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "must be a valite email addres" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user

  def set_current_user
    if session[:user_id]
      Current.user = User.find_by(id: session[:user_id])
    end
  end

  def check_user_login
    if Current.user.nil?
      redirect_to login_path, flash: { :message => "Harus Login Terlebih Dahulu", :type => "danger" }
    end
  end

  def check_user_not_login
    if !Current.user.nil?
      redirect_to admin_dashboard_path, flash: { :message => "Welcome Back", :type => "success" }
    end
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  before_action :check_user_not_login
  skip_before_action :check_user_not_login, only: [:logout]
  layout "login"

  def index
  end

  def store
    user = User.find_by(email: params[:email])
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to admin_dashboard_path, flash: { :message => "Logged in", :type => "success" }
    else
      flash[:message] = "Invalid email or password"
      flash[:type] = "danger"
      render :index
    end
  end

  def forgotpass
  end

  def forgotpassstore
    @user = User.find_by(email: params[:email])

    if @user.present?
      @token = @user.signed_id(purpose: "resetpass", expires_in: 15.minutes)
      PasswordMailer.with(user: @user, token: @token).reset.deliver_now
      redirect_to forgotpassword_path, flash: { :message => "We have sent a link to reset your password in email", :type => "success" }
    else
      flash[:message] = "Email is invalid"
      flash[:type] = "danger"
      render :forgotpass
    end
  end

  def forgotpassedit
    @user = User.find_signed!(params[:token], purpose: "resetpass")
  rescue ActiveSupport::MessageVerifier::InvalidSignature
    redirect_to forgotpassword_path, flash: { :message => "Your token has expired", :type => "danger" }
  end

  def forgotpassupdate
    @user = User.find_signed!(params[:token], purpose: "resetpass")
    if @user.update(password_params)
      redirect_to login_path, flash: { :message => "Your password has reset successfully", :type => "success" }
    else
      flash[:message] = "Token is invalid"
      flash[:type] = "danger"
      render :forgotpass
    end
  end

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end

  def logout
    # set session
    session[:user_id] = nil
    redirect_to home_path, flash: { :message => "Logged out", :type => "success" }
  end
end

app/controllers/mainpages_controller.rb
class MainpagesController < ApplicationController
  def index
  end
end

app/helpers/admin/book_helper.rb
module Admin::BookHelper
end

app/helpers/admin/genre_helper.rb
module Admin::GenreHelper
end

app/helpers/admin/lokasi_helper.rb
module Admin::LokasiHelper
end

app/helpers/admin/tipe_helper.rb
module Admin::TipeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/mainpages_helper.rb
module MainpagesHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <title><%= yield(:title) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <!-- ================== BEGIN core-css ================== -->
    <%= stylesheet_link_tag "adminpage/css/vendor.min.css", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "adminpage/css/app.min.css", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <!-- ================== END core-css ================== -->

</head>

<body>
    <!-- BEGIN #app -->
    <div id="app" class="app">
        <%= render partial: "shared/headeradminpage" %>
        <!-- BEGIN #content -->
        <div id="content" class="app-content">
            <%= yield %>
        </div>
        <!-- END #content -->

        <!-- BEGIN btn-scroll-top -->
        <a href="#" data-click="scroll-top" class="btn-scroll-top fade"><i class="fa fa-arrow-up"></i></a>
        <!-- END btn-scroll-top -->
    </div>
    <!-- END #app -->

    <!-- ================== BEGIN core-js ================== -->
    <script src="<%= javascript_path 'adminpage/js/vendor.min.js'%>"></script>
    <script src="<%= javascript_path 'adminpage/js/app.min.js'%>"></script>
    <!-- ================== END core-js ================== -->

    <!-- ================== BEGIN page-js ================== -->
    <script src="<%= javascript_path 'adminpage/plugins/apexcharts/dist/apexcharts.min.js'%>"></script>
    <script src="<%= javascript_path 'adminpage/js/demo/dashboard.demo.js'%>"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdn.ckeditor.com/4.19.0/basic/ckeditor.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <!-- ================== END page-js ================== -->
    <%= yield(:javascript) %>
    <script>
        (function(i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function() {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '../../www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-53034621-1', 'auto');
        ga('send', 'pageview');
    </script>
</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Mulish:wght@300;400;500;600;700;800;900&display=swap"
        rel="stylesheet">

    <%= stylesheet_link_tag "mainpage/css/bootstrap.min", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "mainpage/css/font-awesome.min", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "mainpage/css/elegant-icons", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "mainpage/css/plyr", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "mainpage/css/owl.carousel.min", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "mainpage/css/slicknav.min", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "mainpage/css/style", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
  </head>

  <body>
    <%= render partial: "shared/headermainpage" %>
    <section class="product spad">
      <div class="container">
        <%= yield %>
      </div>
    </section>
    <%= render partial: "shared/footermainpage" %>

    <script src="<%= javascript_path 'mainpage/js/jquery-3.3.1.min'%>"></script>
    <script src="<%= javascript_path 'mainpage/js/bootstrap.min'%>"></script>
    <script src="<%= javascript_path 'mainpage/js/player'%>"></script>
    <script src="<%= javascript_path 'mainpage/js/jquery.nice-select.min'%>"></script>
    <script src="<%= javascript_path 'mainpage/js/mixitup.min'%>"></script>
    <script src="<%= javascript_path 'mainpage/js/jquery.slicknav'%>"></script>
    <script src="<%= javascript_path 'mainpage/js/owl.carousel.min'%>"></script>
    <script src="<%= javascript_path 'mainpage/js/main'%>"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
  </head>

  <body>
    <div class="container"><%= yield %></div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

app/views/shared/_alertmainpage.html.erb
<% if flash[:message] %>
<div
  class="alert alert-<%= flash[:type] %> alert-dismissible fade show"
  role="alert"
>
  <%= flash[:message] %>
  <button
    type="button"
    class="btn-close"
    data-bs-dismiss="alert"
    aria-label="Close"
  ></button>
</div>
<% end %>

app/views/shared/_footermainpage.html.erb
<footer class="footer">
  <div class="page-up">
    <a href="#" id="scrollToTopButton"><span class="arrow_carrot-up"></span></a>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-lg-3"></div>
      <div class="col-lg-6">
        <div class="footer__nav">
          <ul>
            <li class="active">
              <a href="#">Home</a>
            </li>
            <li><a href="#">Kategori</a></li>
            <li><a href="#">Cari Buku</a></li>
          </ul>
        </div>
      </div>
      <div class="col-lg-3"></div>
    </div>
  </div>
</footer>

app/views/shared/_headeradminpage.html.erb
<!-- BEGIN #header -->
<div id="header" class="app-header">
  <!-- BEGIN mobile-toggler -->
  <div class="mobile-toggler">
    <button type="button" class="menu-toggler" data-toggle="sidebar-mobile">
      <span class="bar"></span>
      <span class="bar"></span>
    </button>
  </div>
  <!-- END mobile-toggler -->

  <!-- BEGIN brand -->
  <div class="brand">
    <div class="desktop-toggler">
      <button type="button" class="menu-toggler" data-toggle="sidebar-minify">
        <span class="bar"></span>
        <span class="bar"></span>
      </button>
    </div>

    <%= link_to "Perpustakaan", admin_dashboard_path, class: "brand-logo" %>
  </div>
  <!-- END brand -->

  <!-- BEGIN menu -->
  <div class="menu">
    <div class="menu-search"></div>
    <div class="menu-item dropdown"></div>
    <div class="menu-item dropdown">
      <a
        href="#"
        data-bs-toggle="dropdown"
        data-bs-display="static"
        class="menu-link"
      >
        <div class="menu-img online">
          <img
            src="<%= image_path('adminpage/img/user/user.jpg') %>"
            alt=""
            class="mw-100 mh-100 rounded-circle"
          />
        </div>
        <div class="menu-text">Admin</div>
      </a>
      <div class="dropdown-menu dropdown-menu-end me-lg-3">
        <%= button_to "Log out", logout_path,class: "dropdown-item d-flex
        align-items-center", method: :delete %>
      </div>
    </div>
  </div>
  <!-- END menu -->
</div>
<!-- END #header -->

<!-- BEGIN #sidebar -->
<div id="sidebar" class="app-sidebar">
  <!-- BEGIN scrollbar -->
  <div class="app-sidebar-content" data-scrollbar="true" data-height="100%">
    <!-- BEGIN menu -->
    <div class="menu">
      <div class="menu-header">Menu</div>
      <div class="menu-item active">
        <a href="<%= admin_dashboard_path %>" class="menu-link">
          <span class="menu-icon"><i class="fa fa-laptop"></i></span>
          <span class="menu-text">Dashboard</span>
        </a>
      </div>
      <div class="menu-item">
        <a href="<%= admin_genre_index_path %>" class="menu-link">
          <span class="menu-icon"><i class="fa fa-bookmark"></i></span>
          <span class="menu-text">Genre Buku</span>
        </a>
      </div>
      <div class="menu-item">
        <a href="<%= admin_location_index_path %>" class="menu-link">
          <span class="menu-icon"><i class="fa fa-location-arrow"></i></span>
          <span class="menu-text">Lokasi Buku</span>
        </a>
      </div>
      <div class="menu-item">
        <a href="<%= admin_type_index_path %>" class="menu-link">
          <span class="menu-icon"><i class="fa fa-tags"></i></span>
          <span class="menu-text">Tipe Buku</span>
        </a>
      </div>
      <div class="menu-item">
        <a href="<%= admin_book_index_path %>" class="menu-link">
          <span class="menu-icon"><i class="fa fa-book"></i></span>
          <span class="menu-text">Buku</span>
        </a>
      </div>
      <div class="menu-item">
        <a href="<%= admin_borrower_index_path %>" class="menu-link">
          <span class="menu-icon"><i class="fa fa-tasks"></i></span>
          <span class="menu-text">Peminjaman</span>
        </a>
      </div>
      <div class="menu-item">
        <a href="<%= admin_member_index_path %>" class="menu-link">
          <span class="menu-icon"><i class="fa fa-user-circle"></i></span>
          <span class="menu-text">Member</span>
        </a>
      </div>
    </div>
    <!-- END menu -->
  </div>
  <!-- END scrollbar -->

  <!-- BEGIN mobile-sidebar-backdrop -->
  <button
    class="app-sidebar-mobile-backdrop"
    data-dismiss="sidebar-mobile"
  ></button>
  <!-- END mobile-sidebar-backdrop -->
</div>
<!-- END #sidebar -->

app/views/shared/_headermainpage.html.erb
<!-- Header Section Begin -->
<header class="header">
  <div class="container">
    <div class="row">
      <div class="col-lg-2">
        <div class="header__logo">
          <a href="#" style="color: white"> App Perpustakaan </a>
        </div>
      </div>
      <div class="col-lg-8">
        <div class="header__nav">
          <nav class="header__menu mobile-menu">
            <ul>
              <li class="active">
                <a href="#">Home</a>
              </li>
              <li><a href="#">Kategori</a></li>
              <li><a href="#">Cari Buku</a></li>
            </ul>
          </nav>
        </div>
      </div>
    </div>
    <div id="mobile-menu-wrap"></div>
  </div>
</header>
<!-- Header End -->