config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "mainpages#index", as: "home"

  # harusnya only guest
  get "login", to: "login#index", as: "login"
  post "login/store", to: "login#store", as: "loginstore"
  get "forgotpassword", to: "login#forgotpass", as: "forgotpassword"
  post "forgotpassword/store", to: "login#forgotpassstore", as: "forgotpasswordstore"
  get "forgotpassword/edit", to: "login#forgotpassedit", as: "forgotpassedit"
  patch "forgotpassword/update", to: "login#forgotpassupdate", as: "forgotpassupdate"

  delete "logout", to: "login#logout", as: "logout"

  # harusnya only admin
  namespace :admin do
    get "dashboard", to: "dashboard#index", as: "dashboard"

    #crud genre
    get "genre", to: "genre#index", as: "genre_index"
    get "genre/add", to: "genre#add", as: "genre_add"
    post "genre/store", to: "genre#store", as: "genre_store"
    get "genre/destroy/:id", to: "genre#destroy", as: "genre_delete"
    get "genre/edit/:id", to: "genre#edit", as: "genre_edit"
    patch "genre/edit/:id", to: "genre#update", as: "genre_update"

    #crud lokasi
    get "location", to: "lokasi#index", as: "location_index"
    get "location/add", to: "lokasi#add", as: "location_add"
    post "location/store", to: "lokasi#store", as: "location_store"
    get "location/destroy/:id", to: "lokasi#destroy", as: "location_delete"
    get "location/edit/:id", to: "lokasi#edit", as: "location_edit"
    patch "location/update/:id", to: "lokasi#update", as: "location_update"

    #crud tipe
    get "type", to: "tipe#index", as: "type_index"
    get "type/add", to: "tipe#add", as: "type_add"
    post "type/store", to: "tipe#store", as: "type_store"
    get "type/destroy/:id", to: "tipe#destroy", as: "type_delete"
    get "type/edit/:id", to: "tipe#edit", as: "type_edit"
    patch "type/update/:id", to: "tipe#update", as: "type_update"

    #crud member
    get "member", to: "member#index", as: "member_index"
    get "member/add", to: "member#add", as: "member_add"
    post "member/store", to: "member#store", as: "member_store"
    get "member/destroy/:id", to: "member#destroy", as: "member_delete"
    get "member/edit/:id", to: "member#edit", as: "member_edit"
    patch "member/update/:id", to: "member#update", as: "member_update"

    #crud buku
    get "book", to: "book#index", as: "book_index"
    get "book/add", to: "book#add", as: "book_add"
    post "book/store", to: "book#store", as: "book_store"
    get "book/destroy/:id", to: "book#destroy", as: "book_delete"
    get "book/edit/:id", to: "book#edit", as: "book_edit"
    patch "book/update/:id", to: "book#update", as: "book_update"

    #crud buku
    get "borrower", to: "borrower#index", as: "borrower_index"
    get "borrower/add", to: "borrower#add", as: "borrower_add"
    post "borrower/store", to: "borrower#store", as: "borrower_store"
    get "borrower/return/:id", to: "borrower#return", as: "borrower_return"
  end

  # api
  namespace :api, defaults: { format: :json } do
    post "authenticate", to: "authentication#authenticate"
    resources :trips, only: [:index]
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  paginates_per 10
  acts_as_paranoid

  validates :name, presence: true
end

app/controllers/admin/genre_controller.rb
class Admin::GenreController < ApplicationController
  before_action :check_user_login
  layout "admin"

  def index
    @genres = Genre.where("name like ?", "%#{params[:search]}%").order(:name).page params[:page]

    if params.has_key?(:page)
      perpage = 10
      page = Integer(params[:page])
      @no = (page * perpage) - perpage
    else
      @no = 0
    end
  end

  def add
    @genre = Genre.new
  end

  def store
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genre_index_path, flash: { :message => "Menambah Genre Berhasil", :type => "success" }
    else
      render :add
    end
  end

  def edit
    @genre = Genre.find(params[:id]) rescue nil
    if @genre.nil?
      redirect_to admin_genre_index_path, flash: { :message => "Data Tidak ditemukan", :type => "warning" }
    end
  end

  def update
    @genre = Genre.find(params[:id]) rescue nil
    if @genre.nil?
      redirect_to admin_genre_index_path, flash: { :message => "Data Tidak ditemukan", :type => "warning" }
    end

    if @genre.update(genre_params)
      redirect_to admin_genre_index_path, flash: { :message => "Mengubah Genre Berhasil", :type => "success" }
    else
      render :edit
    end
  end

  def destroy
    @genre = Genre.find(params[:id]) rescue nil
    if !@genre.nil?
      @genre.destroy
      redirect_to admin_genre_index_path, flash: { :message => "Menghapus Genre Berhasil", :type => "success" }
    else
      redirect_to admin_genre_index_path, flash: { :message => "Data Tidak ditemukan", :type => "warning" }
    end
  end

  private

  def genre_params
    params.required(:genre).permit(:name)
  end
end

app/helpers/admin/genre_helper.rb
module Admin::GenreHelper
end

app/views/admin/genre/add.html.erb
<% content_for :title, "Genre Buku Add" %>
<h1 class="page-header mb-3">Tambah Genre Buku</h1>
<div class="row">
  <div class="col-xl-12">
    <div class="card">
      <div class="card-body">
        <%= render partial: "shared/alertmainpage" %> <%= form_with model:
        @genre, url: admin_genre_store_path, method: :post, multipart: true do
        |form| %>
        <div class="form-group">
          <% invalid = @genre.errors.include?(:name) %>
          <label for="exampleFormControlInput1" class="mb-2">
            Nama Genre Buku
          </label>
          <%= form.text_field :name, class:"form-control #{if invalid then
          "is-invalid" else "" end }", placeholder:"Comedy" %> <% if invalid %>
          <div class="invalid-feedback d-block">
            <% @genre.errors.full_messages_for(:name).each do |error_message| %>
            <%= error_message %>. <br />
            <% end %>
          </div>
          <% end %>
        </div>
        <hr />
        <div class="text-end">
          <a href="<%= admin_genre_index_path %>" class="btn btn-danger">
            Batal
          </a>
          <%= form.submit "Simpan", class:"btn btn-primary" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<!-- END row -->

app/views/admin/genre/edit.html.erb
<% content_for :title, "Genre Buku Edit" %>
<h1 class="page-header mb-3">Edit Genre Buku</h1>
<div class="row">
  <div class="col-xl-12">
    <div class="card">
      <div class="card-body">
        <%= render partial: "shared/alertmainpage" %> <%= form_with model:
        @genre, url: admin_genre_update_path, method: :patch, multipart: true do
        |form| %>
        <div class="form-group">
          <% invalid = @genre.errors.include?(:name) %>
          <label for="exampleFormControlInput1" class="mb-2">
            Nama Genre Buku
          </label>
          <%= form.text_field :name, class:"form-control #{if invalid then
          "is-invalid" else "" end }", placeholder:"Comedy" %> <% if invalid %>
          <div class="invalid-feedback d-block">
            <% @genre.errors.full_messages_for(:name).each do |error_message| %>
            <%= error_message %>. <br />
            <% end %>
          </div>
          <% end %>
        </div>
        <hr />
        <div class="text-end">
          <a href="<%= admin_genre_index_path %>" class="btn btn-danger">
            Batal
          </a>
          <%= form.submit "Simpan", class:"btn btn-primary" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<!-- END row -->

app/views/admin/genre/index.html.erb
<% content_for :title, "Genre Buku" %>
<h1 class="page-header mb-3">List Genre Buku</h1>
<div class="row">
  <div class="col-xl-12">
    <div class="card">
      <div class="card-header row">
        <div class="col-md-8">
          <a href="<%= admin_genre_add_path %>" class="btn btn-primary"
            ><i class="fa fa-plus"></i> Tambah Genre Buku</a
          >
        </div>
        <div class="col-md-4">
          <div class="text-end">
            <form action="" method="get">
              <div class="input-group">
                <input
                  type="search"
                  class="form-control"
                  name="search"
                  value="<%= params[:search] %>"
                  placeholder="Cari...."
                />
                <div class="input-group-append">
                  <button type="submit" class="btn btn-primary">
                    <i class="fa fa-search"></i> Cari
                  </button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
      <div class="card-body">
        <%= render partial: "shared/alertmainpage" %>
        <div class="table-responsive">
          <table class="table table-striped">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Nama Genre Buku</th>
                <th scope="col">Aksi</th>
              </tr>
            </thead>
            <tbody>
              <% @genres.each do |genre| %>
              <tr>
                <td><%= @no+=1 %></td>
                <td><%= genre.name %></td>
                <td>
                  <a
                    href="<%= admin_genre_edit_path(genre.id) %>"
                    class="btn btn-sm btn-primary"
                    ><i class="fa fa-edit"></i> Edit</a
                  >
                  <button
                    data-delete="<%= admin_genre_delete_path(genre.id) %>"
                    class="btn btn-sm btn-danger btndelete"
                  >
                    <i class="fa fa-trash"></i> Hapus
                  </button>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <div style="display: flex; justify-content: center">
          <%= paginate @genres, inner_window: 3 %>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- END row -->

<% content_for :javascript do %>
<script>
  $(".btndelete").click(function () {
    var linkdelete = $(this).data("delete");
    const swalWithBootstrapButtons = Swal.mixin({
      customClass: {
        confirmButton: "btn btn-danger",
        cancelButton: "btn btn-success mr-1",
      },
      buttonsStyling: {
        cancelButton: "margin-right: 1rem;",
      },
    });

    swalWithBootstrapButtons
      .fire({
        title: "Apakah Yakin Ingin ?",
        text: "Ingin Menghapus Data Tersebut",
        icon: "warning",
        showCancelButton: true,
        confirmButtonText: "Hapus",
        cancelButtonText: "Batal",
        reverseButtons: true,
      })
      .then((result) => {
        if (result.isConfirmed) {
          window.location.href = linkdelete;
        }
      });
  });
</script>
<% end %>