config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "mainpages#index", as: "home"

  # harusnya only guest
  get "login", to: "login#index", as: "login"
  post "login/store", to: "login#store", as: "loginstore"
  get "forgotpassword", to: "login#forgotpass", as: "forgotpassword"
  post "forgotpassword/store", to: "login#forgotpassstore", as: "forgotpasswordstore"
  get "forgotpassword/edit", to: "login#forgotpassedit", as: "forgotpassedit"
  patch "forgotpassword/update", to: "login#forgotpassupdate", as: "forgotpassupdate"

  delete "logout", to: "login#logout", as: "logout"

  # harusnya only admin
  namespace :admin do
    get "dashboard", to: "dashboard#index", as: "dashboard"

    #crud genre
    get "genre", to: "genre#index", as: "genre_index"
    get "genre/add", to: "genre#add", as: "genre_add"
    post "genre/store", to: "genre#store", as: "genre_store"
    get "genre/destroy/:id", to: "genre#destroy", as: "genre_delete"
    get "genre/edit/:id", to: "genre#edit", as: "genre_edit"
    patch "genre/edit/:id", to: "genre#update", as: "genre_update"

    #crud lokasi
    get "location", to: "lokasi#index", as: "location_index"
    get "location/add", to: "lokasi#add", as: "location_add"
    post "location/store", to: "lokasi#store", as: "location_store"
    get "location/destroy/:id", to: "lokasi#destroy", as: "location_delete"
    get "location/edit/:id", to: "lokasi#edit", as: "location_edit"
    patch "location/update/:id", to: "lokasi#update", as: "location_update"

    #crud tipe
    get "type", to: "tipe#index", as: "type_index"
    get "type/add", to: "tipe#add", as: "type_add"
    post "type/store", to: "tipe#store", as: "type_store"
    get "type/destroy/:id", to: "tipe#destroy", as: "type_delete"
    get "type/edit/:id", to: "tipe#edit", as: "type_edit"
    patch "type/update/:id", to: "tipe#update", as: "type_update"

    #crud member
    get "member", to: "member#index", as: "member_index"
    get "member/add", to: "member#add", as: "member_add"
    post "member/store", to: "member#store", as: "member_store"
    get "member/destroy/:id", to: "member#destroy", as: "member_delete"
    get "member/edit/:id", to: "member#edit", as: "member_edit"
    patch "member/update/:id", to: "member#update", as: "member_update"

    #crud buku
    get "book", to: "book#index", as: "book_index"
    get "book/add", to: "book#add", as: "book_add"
    post "book/store", to: "book#store", as: "book_store"
    get "book/destroy/:id", to: "book#destroy", as: "book_delete"
    get "book/edit/:id", to: "book#edit", as: "book_edit"
    patch "book/update/:id", to: "book#update", as: "book_update"

    #crud buku
    get "borrower", to: "borrower#index", as: "borrower_index"
    get "borrower/add", to: "borrower#add", as: "borrower_add"
    post "borrower/store", to: "borrower#store", as: "borrower_store"
    get "borrower/return/:id", to: "borrower#return", as: "borrower_return"
  end

  # api
  namespace :api, defaults: { format: :json } do
    post "authenticate", to: "authentication#authenticate"
    resources :trips, only: [:index]
  end
end

app/models/book.rb
class Book < ApplicationRecord
  paginates_per 10
  acts_as_paranoid

  has_many :book_categories

  validates :location_id, presence: true
  validates :type_id, presence: true
  validates :name, presence: true
  validates :book_total, presence: true
  validates :book_total_remaining, presence: true
  mount_uploader :bookphoto, MemberPhotoUploader
end

app/controllers/admin/book_controller.rb
class Admin::BookController < ApplicationController
  before_action :check_user_login
  layout "admin"

  def index
    @books = Book.where("name like ?", "%#{params[:search]}%").order(:name).page params[:page]

    if params.has_key?(:page)
      perpage = 10
      page = Integer(params[:page])
      @no = (page * perpage) - perpage
    else
      @no = 0
    end
  end

  def add
    @book = Book.new
    @type = Type.all.map { |type| [type.name, type.id] }
    @location = Location.all.map { |type| [type.name, type.id] }
    @genre = Genre.all.map { |type| [type.name, type.id] }
  end

  def store
    params[:book][:book_total_remaining] = params[:book][:book_total]
    @book = Book.new(book_params)
    if @book.save
      params[:book][:genre].each do |i|
        if i != ""
          params[:book_id] = @book.id
          params[:genre_id] = i
          bookcategories = BookCategory.new(book_category_params)
          bookcategories.save
        end
      end
      redirect_to admin_book_index_path, flash: { :message => "Menambah Buku Berhasil", :type => "success" }
    else
      @type = Type.all.map { |type| [type.name, type.id] }
      @location = Location.all.map { |type| [type.name, type.id] }
      @genre = Genre.all.map { |type| [type.name, type.id] }
      render :add
    end
  end

  def edit
    @book = Book.find(params[:id]) rescue nil
    if @book.nil?
      redirect_to admin_book_index_path, flash: { :message => "Data Tidak ditemukan", :type => "warning" }
    end
    @book.bookphoto.cache!
    @type = Type.all.map { |type| [type.name, type.id] }
    @location = Location.all.map { |type| [type.name, type.id] }
    @genre = Genre.all.map { |type| [type.name, type.id] }
  end

  def update
    @book = Book.find(params[:id]) rescue nil
    if @book.nil?
      redirect_to admin_book_index_path, flash: { :message => "Data Tidak ditemukan", :type => "warning" }
    end

    if @book.update(book_params)
      BookCategory.where(:book_id => params[:id]).destroy_all
      params[:book][:genre].each do |i|
        if i != ""
          params[:book_id] = params[:id]
          params[:genre_id] = i
          bookcategories = BookCategory.new(book_category_params)
          bookcategories.save
        end
      end
      redirect_to admin_book_index_path, flash: { :message => "Mengubah Buku Berhasil", :type => "success" }
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id]) rescue nil
    if !@book.nil?
      @book.remove_bookphoto!
      @book.save
      @book.destroy
      BookCategory.where(:book_id => params[:id]).destroy_all
      redirect_to admin_book_index_path, flash: { :message => "Menghapus Buku Berhasil", :type => "success" }
    else
      redirect_to admin_book_index_path, flash: { :message => "Data Tidak ditemukan", :type => "warning" }
    end
  end

  def book_params
    params.required(:book).permit(:name, :publisher, :writer, :release_date, :page_total, :book_total, :book_total_remaining, :type_id, :location_id, :description, :bookphoto)
  end

  def book_category_params
    params.permit(:book_id, :genre_id)
  end
end

app/helpers/admin/book_helper.rb
module Admin::BookHelper
end

app/views/admin/book/add.html.erb
<% content_for :title, "Buku Add" %>
<h1 class="page-header mb-3">Tambah Buku</h1>
<div class="row">
  <div class="col-xl-12">
    <div class="card">
      <div class="card-body">
        <%= render partial: "shared/alertmainpage" %> <%= form_with model:
        @book, url: admin_book_store_path, method: :post, multipart: true do
        |form| %>
        <div class="form-row row">
          <div class="form-group col-md-6">
            <% invalid = @book.errors.include?(:name) %>
            <label for="inputPassword4">Judul Buku</label>
            <%= form.text_field :name, class:"form-control #{if invalid then
            "is-invalid" else "" end }", placeholder:"harry potter" %> <% if
            invalid %>
            <div class="invalid-feedback d-block">
              <% @book.errors.full_messages_for(:name).each do |error_message|
              %> <%= error_message %>. <br />
              <% end %>
            </div>
            <% end %>
          </div>
          <div class="form-group col-md-6">
            <% invalid = @book.errors.include?(:publisher) %>
            <label for="inputEmail4">Penerbit</label>
            <%= form.text_field :publisher, class:"form-control #{if invalid
            then "is-invalid" else "" end }", placeholder:"Publisher 1" %> <% if
            invalid %>
            <div class="invalid-feedback d-block">
              <% @book.errors.full_messages_for(:publisher).each do
              |error_message| %> <%= error_message %>. <br />
              <% end %>
            </div>
            <% end %>
          </div>
        </div>
        <div class="form-row mt-3 row">
          <div class="form-group col-md-6">
            <% invalid = @book.errors.include?(:writer) %>
            <label for="inputPassword4">Penulis</label>
            <%= form.text_field :writer, class:"form-control #{if invalid then
            "is-invalid" else "" end }", placeholder:"anwar" %> <% if invalid %>
            <div class="invalid-feedback d-block">
              <% @book.errors.full_messages_for(:writer).each do |error_message|
              %> <%= error_message %>. <br />
              <% end %>
            </div>
            <% end %>
          </div>
          <div class="form-group col-md-6">
            <% invalid = @book.errors.include?(:release_date) %>
            <label for="inputEmail4">Tanggal Rilis</label>
            <%= form.date_field :release_date, class:"form-control #{if invalid
            then "is-invalid" else "" end }", placeholder:"" %> <% if invalid %>
            <div class="invalid-feedback d-block">
              <% @book.errors.full_messages_for(:release_date).each do
              |error_message| %> <%= error_message %>. <br />
              <% end %>
            </div>
            <% end %>
          </div>
        </div>
        <div class="form-row mt-3 row">
          <div class="form-group col-md-6">
            <% invalid = @book.errors.include?(:page_total) %>
            <label for="inputPassword4">Total Halaman</label>
            <%= form.number_field :page_total, class:"form-control #{if invalid
            then "is-invalid" else "" end }", placeholder:"300" %> <% if invalid
            %>
            <div class="invalid-feedback d-block">
              <% @book.errors.full_messages_for(:page_total).each do
              |error_message| %> <%= error_message %>. <br />
              <% end %>
            </div>
            <% end %>
          </div>
          <div class="form-group col-md-6">
            <% invalid = @book.errors.include?(:book_total) %>
            <label for="inputEmail4">Total Buku</label>
            <%= form.number_field :book_total, class:"form-control #{if invalid
            then "is-invalid" else "" end }", placeholder:"10" %> <% if invalid
            %>
            <div class="invalid-feedback d-block">
              <% @book.errors.full_messages_for(:book_total).each do
              |error_message| %> <%= error_message %>. <br />
              <% end %>
            </div>
            <% end %>
          </div>
        </div>
        <div class="form-row mt-3 row">
          <div class="form-group col-md-6">
            <% invalid = @book.errors.include?(:type_id) %>
            <label for="inputPassword4">Tipe Buku</label>
            <%= form.select :type_id,options_for_select(@type),{},
            class:"form-control #{if invalid then "is-invalid" else "" end }",
            placeholder:"Pilih Jenis Kelamin" %> <% if invalid %>
            <div class="invalid-feedback d-block">
              <% @book.errors.full_messages_for(:type_id).each do
              |error_message| %> <%= error_message %>. <br />
              <% end %>
            </div>
            <% end %>
          </div>
          <div class="form-group col-md-6">
            <% invalid = @book.errors.include?(:location_id) %>
            <label for="inputEmail4">Lokasi Buku</label>
            <%= form.select :location_id,options_for_select(@location),{},
            class:"form-control #{if invalid then "is-invalid" else "" end }",
            placeholder:"Pilih Jenis Kelamin" %> <% if invalid %>
            <div class="invalid-feedback d-block">
              <% @book.errors.full_messages_for(:location_id).each do
              |error_message| %> <%= error_message %>. <br />
              <% end %>
            </div>
            <% end %>
          </div>
        </div>
        <div class="form-row mt-3 row">
          <div class="form-group col-md-6">
            <% invalid = @book.errors.include?(:bookphoto) %>
            <label for="inputPassword4">Foto Buku</label>
            <%= form.file_field :bookphoto, class:"form-control #{if invalid
            then "is-invalid" else "" end }", placeholder:"Islam" %> <% if
            invalid %>
            <div class="invalid-feedback d-block">
              <% @book.errors.full_messages_for(:bookphoto).each do
              |error_message| %> <%= error_message %>. <br />
              <% end %>
            </div>
            <% end %>
          </div>
          <div class="form-group col-md-6">
            <% invalid = @book.errors.include?(:genre) %>
            <label for="inputEmail4">Genre Buku</label>
            <%= form.select :genre, options_for_select(@genre),{},:multiple =>
            true, class:"form-control #{if invalid then "is-invalid" else "" end
            }", placeholder:"Pilih Jenis Kelamin" %> <% if invalid %>
            <div class="invalid-feedback d-block">
              <% @book.errors.full_messages_for(:genre).each do |error_message|
              %> <%= error_message %>. <br />
              <% end %>
            </div>
            <% end %>
          </div>
        </div>
        <div class="form-group col-md-12 mt-3">
          <% invalid = @book.errors.include?(:description) %>
          <label for="inputPassword4">Alamat</label>
          <%= form.text_area :description, class:"form-control #{if invalid then
          "is-invalid" else "" end }", placeholder:"Jln kota bandung" %> <% if
          invalid %>
          <div class="invalid-feedback d-block">
            <% @book.errors.full_messages_for(:description).each do
            |error_message| %> <%= error_message %>. <br />
            <% end %>
          </div>
          <% end %>
        </div>
        <hr />
        <div class="text-end">
          <a href="<%= admin_book_index_path %>" class="btn btn-danger">
            Batal
          </a>
          <%= form.submit "Simpan", class:"btn btn-primary" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<!-- END row -->

<% content_for :javascript do %>
<script>
  CKEDITOR.replace("book_description");
</script>
<script>
  $(document).ready(function () {
    $("#book_genre").select2({
      placeholder: "Pilih Genre Buku",
      allowClear: true,
    });

    $("#book_type_id").select2({
      placeholder: "Pilih Tipe Buku",
      allowClear: true,
    });

    $("#book_location_id").select2({
      placeholder: "Pilih Lokasi Buku",
      allowClear: true,
    });
  });
</script>
<% end %>

app/views/admin/book/edit.html.erb
<% content_for :title, "Buku Edit" %>
<h1 class="page-header mb-3">Edit Buku</h1>
<div class="row">
  <div class="col-xl-12">
    <div class="card">
      <div class="card-body">
        <%= render partial: "shared/alertmainpage" %>
        <br />
        <%= form_with model:@book, url: admin_book_update_path, method: :patch,
        multipart:true do |form| %>
        <div class="form-row row">
          <div class="form-group col-md-6">
            <% invalid = @book.errors.include?(:name) %>
            <label for="inputPassword4">Judul Buku</label>
            <%= form.text_field :name, class:"form-control #{if invalid then
            "is-invalid" else "" end }", placeholder:"harry potter" %> <% if
            invalid %>
            <div class="invalid-feedback d-block">
              <% @book.errors.full_messages_for(:name).each do |error_message|
              %> <%= error_message %>. <br />
              <% end %>
            </div>
            <% end %>
          </div>
          <div class="form-group col-md-6">
            <% invalid = @book.errors.include?(:publisher) %>
            <label for="inputEmail4">Penerbit</label>
            <%= form.text_field :publisher, class:"form-control #{if invalid
            then "is-invalid" else "" end }", placeholder:"Publisher 1" %> <% if
            invalid %>
            <div class="invalid-feedback d-block">
              <% @book.errors.full_messages_for(:publisher).each do
              |error_message| %> <%= error_message %>. <br />
              <% end %>
            </div>
            <% end %>
          </div>
        </div>
        <div class="form-row mt-3 row">
          <div class="form-group col-md-6">
            <% invalid = @book.errors.include?(:writer) %>
            <label for="inputPassword4">Penulis</label>
            <%= form.text_field :writer, class:"form-control #{if invalid then
            "is-invalid" else "" end }", placeholder:"anwar" %> <% if invalid %>
            <div class="invalid-feedback d-block">
              <% @book.errors.full_messages_for(:writer).each do |error_message|
              %> <%= error_message %>. <br />
              <% end %>
            </div>
            <% end %>
          </div>
          <div class="form-group col-md-6">
            <% invalid = @book.errors.include?(:release_date) %>
            <label for="inputEmail4">Tanggal Rilis</label>
            <%= form.date_field :release_date, class:"form-control #{if invalid
            then "is-invalid" else "" end }", placeholder:"" %> <% if invalid %>
            <div class="invalid-feedback d-block">
              <% @book.errors.full_messages_for(:release_date).each do
              |error_message| %> <%= error_message %>. <br />
              <% end %>
            </div>
            <% end %>
          </div>
        </div>
        <div class="form-row mt-3 row">
          <div class="form-group col-md-6">
            <% invalid = @book.errors.include?(:page_total) %>
            <label for="inputPassword4">Total Halaman</label>
            <%= form.number_field :page_total, class:"form-control #{if invalid
            then "is-invalid" else "" end }", placeholder:"300" %> <% if invalid
            %>
            <div class="invalid-feedback d-block">
              <% @book.errors.full_messages_for(:page_total).each do
              |error_message| %> <%= error_message %>. <br />
              <% end %>
            </div>
            <% end %>
          </div>
          <div class="form-group col-md-6">
            <% invalid = @book.errors.include?(:book_total) %>
            <label for="inputEmail4">Total Buku</label>
            <%= form.number_field :book_total, class:"form-control #{if invalid
            then "is-invalid" else "" end }", placeholder:"10" %> <% if invalid
            %>
            <div class="invalid-feedback d-block">
              <% @book.errors.full_messages_for(:book_total).each do
              |error_message| %> <%= error_message %>. <br />
              <% end %>
            </div>
            <% end %>
          </div>
        </div>
        <div class="form-row mt-3 row">
          <div class="form-group col-md-6">
            <% invalid = @book.errors.include?(:type_id) %>
            <label for="inputPassword4">Tipe Buku</label>
            <%= form.select :type_id,options_for_select(@type),{},
            class:"form-control #{if invalid then "is-invalid" else "" end }",
            placeholder:"Pilih Jenis Kelamin" %> <% if invalid %>
            <div class="invalid-feedback d-block">
              <% @book.errors.full_messages_for(:type_id).each do
              |error_message| %> <%= error_message %>. <br />
              <% end %>
            </div>
            <% end %>
          </div>
          <div class="form-group col-md-6">
            <% invalid = @book.errors.include?(:location_id) %>
            <label for="inputEmail4">Lokasi Buku</label>
            <%= form.select :location_id,options_for_select(@location),{},
            class:"form-control #{if invalid then "is-invalid" else "" end }",
            placeholder:"Pilih Jenis Kelamin" %> <% if invalid %>
            <div class="invalid-feedback d-block">
              <% @book.errors.full_messages_for(:location_id).each do
              |error_message| %> <%= error_message %>. <br />
              <% end %>
            </div>
            <% end %>
          </div>
        </div>
        <div class="form-row mt-3 row">
          <div class="form-group col-md-6">
            <% invalid = @book.errors.include?(:bookphoto) %>
            <label for="inputPassword4">Foto Buku</label>
            <%= form.file_field :bookphoto, class:"form-control #{if invalid
            then "is-invalid" else "" end }", placeholder:"Islam" %> <%=
            form.hidden_field :bookphoto_cache %> <% if invalid %>
            <div class="invalid-feedback d-block">
              <% @book.errors.full_messages_for(:bookphoto).each do
              |error_message| %> <%= error_message %>. <br />
              <% end %>
            </div>
            <% end %>
          </div>
          <div class="form-group col-md-6">
            <% invalid = @book.errors.include?(:genre) %>
            <label for="inputEmail4">Genre Buku</label>
            <%= form.select :genre, options_for_select(@genre),{},:multiple =>
            true, class:"form-control #{if invalid then "is-invalid" else "" end
            }", placeholder:"Pilih Jenis Kelamin" %> <% if invalid %>
            <div class="invalid-feedback d-block">
              <% @book.errors.full_messages_for(:genre).each do |error_message|
              %> <%= error_message %>. <br />
              <% end %>
            </div>
            <% end %>
          </div>
        </div>
        <div class="form-group col-md-12 mt-3">
          <% invalid = @book.errors.include?(:description) %>
          <label for="inputPassword4">Alamat</label>
          <%= form.text_area :description, class:"form-control #{if invalid then
          "is-invalid" else "" end }", placeholder:"Jln kota bandung" %> <% if
          invalid %>
          <div class="invalid-feedback d-block">
            <% @book.errors.full_messages_for(:description).each do
            |error_message| %> <%= error_message %>. <br />
            <% end %>
          </div>
          <% end %>
        </div>
        <hr />
        <div class="text-end">
          <a href="<%= admin_book_index_path %>" class="btn btn-danger">
            Batal
          </a>
          <%= form.submit "Simpan", class:"btn btn-primary" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<!-- END row -->

<% content_for :javascript do %>
<script>
  CKEDITOR.replace("book_description");
</script>
<% @book.book_categories.each do |book_category| %>
<script>
  $("#book_genre option[value='<%= book_category.genre_id %>']").prop(
    "selected",
    true
  );
</script>
<% end %>
<script>
  $(document).ready(function () {
    $("#book_genre").select2({
      placeholder: "Pilih Genre Buku",
      allowClear: true,
    });

    $("#book_type_id").select2({
      placeholder: "Pilih Tipe Buku",
      allowClear: true,
    });

    $("#book_location_id").select2({
      placeholder: "Pilih Lokasi Buku",
      allowClear: true,
    });
  });
</script>
<% end %>

app/views/admin/book/index.html.erb
<% content_for :title, "Buku" %>
<h1 class="page-header mb-3">List Buku</h1>
<div class="row">
  <div class="col-xl-12">
    <div class="card">
      <div class="card-header row">
        <div class="col-md-8">
          <a href="<%= admin_book_add_path %>" class="btn btn-primary"
            ><i class="fa fa-plus"></i> Tambah Buku</a
          >
        </div>
        <div class="col-md-4">
          <div class="text-end">
            <form action="" method="get">
              <div class="input-group">
                <input
                  type="search"
                  class="form-control"
                  name="search"
                  value="<%= params[:search] %>"
                  placeholder="Cari...."
                />
                <div class="input-group-append">
                  <button type="submit" class="btn btn-primary">
                    <i class="fa fa-search"></i> Cari
                  </button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
      <div class="card-body">
        <%= render partial: "shared/alertmainpage" %>
        <div class="table-responsive">
          <table class="table table-striped">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Nama Buku</th>
                <th scope="col">Penerbit</th>
                <th scope="col">Kategori Buku</th>
                <th scope="col">Total Buku Serupa</th>
                <th scope="col">Sisa Buku Serupa</th>
                <th scope="col">Aksi</th>
              </tr>
            </thead>
            <tbody>
              <% @books.each do |book| %>
              <tr>
                <td><%= @no+=1 %></td>
                <td><%= book.name %></td>
                <td><%= book.publisher %></td>
                <td>
                  <ul>
                    <% book.book_categories.each do |book_category| %>
                    <li><%= book_category.genre.name %></li>
                    <% end %>
                  </ul>
                </td>
                <td><%= book.book_total %></td>
                <td><%= book.book_total_remaining %></td>
                <td>
                  <a
                    href="<%= admin_book_edit_path(book.id) %>"
                    class="btn btn-sm btn-primary"
                    ><i class="fa fa-edit"></i> Edit</a
                  >
                  <button
                    data-delete="<%= admin_book_delete_path(book.id) %>"
                    class="btn btn-sm btn-danger btndelete"
                  >
                    <i class="fa fa-trash"></i> Hapus
                  </button>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <div style="display: flex; justify-content: center">
          <%= paginate @books, inner_window: 3 %>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- END row -->

<% content_for :javascript do %>
<script>
  $(".btndelete").click(function () {
    var linkdelete = $(this).data("delete");
    const swalWithBootstrapButtons = Swal.mixin({
      customClass: {
        confirmButton: "btn btn-danger",
        cancelButton: "btn btn-success mr-1",
      },
      buttonsStyling: {
        cancelButton: "margin-right: 1rem;",
      },
    });

    swalWithBootstrapButtons
      .fire({
        title: "Apakah Yakin Ingin ?",
        text: "Ingin Menghapus Data Tersebut",
        icon: "warning",
        showCancelButton: true,
        confirmButtonText: "Hapus",
        cancelButtonText: "Batal",
        reverseButtons: true,
      })
      .then((result) => {
        if (result.isConfirmed) {
          window.location.href = linkdelete;
        }
      });
  });
</script>
<% end %>